### ISSUE TITLE
maven-javadoc-plugin eclipse error

### ISSUE THREAD

**Issue by AbdelRahmaneB** [McPringle/sportchef#299]
I got this error when trying to import the project into eclipse : 
```
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:javadoc (execution: generate-service-docs, phase: generate-resources)
```
Should it be fixed in the POM? Or should I find a workaround without  modifying it?

**Comment by McPringle** [comment]
Thank you very much for your interest in _SportChef_. Can you please try to checkout and build it without Eclipse to see if the problem is Eclipse related or not? Please try this:

```
git clone git@github.com:McPringle/sportchef.git
cd sportchef
mvn clean package
```

Hopefully everything will be okay and the output should look like this (at the end):

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:23 min
[INFO] Finished at: 2016-11-14T14:20:26+01:00
[INFO] Final Memory: 35M/479M
[INFO] ------------------------------------------------------------------------
```

If you then take a look at the `target` directory you should see a file named `sportchef.war`.

Please respond with the result of your local build.

Enjoy your life
McPringle

**Comment by AbdelRahmaneB** [comment]
Thank you for your response,
When I run the `mvn clean package` I got this : 

```

Results :

Tests run: 13, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- exec-maven-plugin:1.5.0:exec (default) @ sportchef ---
[ERROR] Command execution failed.
java.io.IOException: Cannot run program "C:\Users\Utilisateur\AppData\Roaming\npm\bower" (in directory "E:\Util
isateur\Documents\GitHub\tmp\sportchef"): CreateProcess error=193, %1 n?est pas une application Win32 valide
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
        at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:
116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:
80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreade
dBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.IOException: CreateProcess error=193, %1 n?est pas une application Win32 valide
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 30 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:15 min
[INFO] Finished at: 2016-11-15T11:46:17+00:00
[INFO] Final Memory: 32M/306M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (default) on project sportchef: C
ommand execution failed. Cannot run program "C:\Users\Utilisateur\AppData\Roaming\npm\bower" (in directory "E:\
Utilisateur\Documents\GitHub\tmp\sportchef"): CreateProcess error=193, %1 n?est pas une application Win32 valid
e -> [Help 1]

```

To test, I removed to bower installation from the POM, and executed those commands : 

```
mvn clean
bower install
mvn package
```

 then I got a Build Success. But when I try to deploy the war to payara/glassfish servers, I got : 
`Error occurred during deployment: Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton AutoInstall`

**Comment by McPringle** [comment]
If it is okay for you please wait a few days and try again later. We are splitting this repo up in smaller ones for microservices. This work should be finished by end of the next week. I hope your problem will be solved by then, because we use a new build system (gradle), a new application server (Payara Micro) and deployment mechanism (docker-compose).
